---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stirling-pdf

helmCharts:
  - name: stirling-pdf
    repo: oci://registry.example.com/homelab/helm-charts
    version: 1.0.0
    releaseName: stirling-pdf
    namespace: stirling-pdf
    valuesFile: values.yaml

resources:
  - ingress
