---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: affine-ingressroute
  namespace: affine
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`affine.example.com`)
      services:
        - kind: Service
          name: affine
          port: 80
