---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Wave 0 - Core infrastructure
  - argocd.yaml
  - cert-manager.yaml
  - sealed-secrets.yaml

  # Wave 1 - Networking and storage
  - metallb.yaml
  - traefik.yaml
  - longhorn.yaml

  # Wave 3 - Additional services
  - external-services.yaml
  - rancher.yaml
  - cloudflared.yaml
  # - monitoring.yaml
