---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: affine

helmCharts:
  - name: affine
    repo: oci://registry.example.com/homelab/helm-charts
    version: 1.0.6
    releaseName: affine
    namespace: affine

resources:
  - ingress
  - secrets
