---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: searxng-ingressroute
  namespace: searxng
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`search.example.com`)
      services:
        - kind: Service
          name: searxng
          port: 8080
