---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omni-tools

helmCharts:
  - name: omni-tools
    repo: oci://registry.example.com/homelab/helm-charts
    version: 1.0.0
    releaseName: omni-tools
    namespace: omni-tools
    # valuesFile: values.yaml

resources:
  - ingress
