---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: valkey

helmCharts:
  - name: valkey
    repo: https://charts.bitnami.com/bitnami
    version: 5.1.0
    releaseName: valkey
    namespace: valkey
    valuesFile: values.yaml

resources:
  - secrets
