---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ingressroute
  namespace: cattle-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`rancher.example.com`)
      services:
        - kind: Service
          name: rancher
          port: 80
