---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: searxng

helmCharts:
  - name: searxng
    repo: oci://registry.example.com/homelab/helm-charts
    version: 1.0.7
    releaseName: searxng
    namespace: searxng
    valuesFile: values.yaml

resources:
  - ingress
  - secrets
