---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: privatebin

helmCharts:
  - name: privatebin
    repo: oci://registry.example.com/homelab/helm-charts
    version: 1.0.0
    releaseName: privatebin
    namespace: privatebin
    valuesFile: values.yaml

resources:
  - ingress
