---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: freshrss-ingressroute
  namespace: freshrss
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`rss.example.com`)
      services:
        - kind: Service
          name: freshrss
          port: 80
