---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  # - example-com-wildcard-tls-sealed.yaml
  #   Pre-saved certificate secret (SealedSecret) to avoid Let's Encrypt
  # DO NOT UNCOMMENT: certificate-prod.yaml
  # We use the pre-saved secret (example-com-wildcard-tls-sealed.yaml) instead
  # to avoid rate limits
  - certificate-prod.yaml
  # ONLY FOR TESTING: certificate-staging.yaml
  # - certificate-staging.yaml
