---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.2.3/manifests/install.yaml
  - ingress
  - secrets

patches:
  - path: patches/argocd-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: patches/argocd-cmd-params-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
  - path: patches/argocd-ssh-known-hosts-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-ssh-known-hosts-cm
  - path: patches/argocd-repo-server-deployment-patch.yaml
    target:
      kind: Deployment
      name: argocd-repo-server

images:
  - name: quay.io/argoproj/argocd
    # yamllint disable-line rule:line-length
    newTag: v3.2.3@sha256:9ab6baab65a6b283044a7d7b7dbe50f589564de9c8898d67c77d84b2b5df46bc
