---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

helmCharts:
  - name: cloudflared
    repo: oci://registry.example.com/homelab/helm-charts
    version: 1.0.0
    releaseName: cloudflared
    namespace: cloudflared
    valuesFile: values.yaml

resources:
  - secrets
