---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-1-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ag1.example.com`)
      services:
        - kind: Service
          name: adguard-1
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-2-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ag2.example.com`)
      services:
        - kind: Service
          name: adguard-2
          port: 80
