---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: duplicati-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`duplicati.example.com`)
      services:
        - kind: Service
          name: duplicati
          port: 8200
