---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nextcloud.example.com`)
      services:
        - kind: Service
          name: nextcloud
          port: 8008
          scheme: http
