---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: semaphore-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`semaphore.example.com`)
      services:
        - kind: Service
          name: semaphore
          port: 3000
