---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`bazarr.example.com`)
      services:
        - kind: Service
          name: bazarr
          port: 6767
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: notifiarr-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`notifiarr.example.com`)
      services:
        - kind: Service
          name: notifiarr
          port: 5454
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: overseerr-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`overseerr.example.com`)
      services:
        - kind: Service
          name: overseerr
          port: 5055
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`plex.example.com`)
      services:
        - kind: Service
          name: plex
          port: 32400
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`prowlarr.example.com`)
      services:
        - kind: Service
          name: prowlarr
          port: 9696
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`qbit.example.com`)
      services:
        - kind: Service
          name: qbittorrent
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`radarr.example.com`)
      services:
        - kind: Service
          name: radarr
          port: 7878
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`sonarr.example.com`)
      services:
        - kind: Service
          name: sonarr
          port: 8989
