---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`unifi.example.com`)
      services:
        - kind: Service
          name: unifi
          port: 8443
          serversTransport: unifi-st
