---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cattle-system

helmCharts:
  - name: rancher
    repo: https://releases.rancher.com/server-charts/stable
    version: 2.13.1
    releaseName: rancher
    namespace: cattle-system
    valuesFile: values.yaml

resources:
  - ingress/
