---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: it-tools

helmCharts:
  - name: it-tools
    repo: oci://registry.example.com/homelab/helm-charts
    version: 1.0.0
    releaseName: it-tools
    namespace: it-tools
    valuesFile: values.yaml

resources:
  - ingress
