---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgresql

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 18.2.0
    releaseName: postgresql
    namespace: postgresql
    valuesFile: values.yaml

resources:
  - jobs
  - secrets
