---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

helmCharts:
  - name: home-assistant
    repo: oci://registry.example.com/homelab/helm-charts
    version: 1.0.0
    releaseName: home-assistant
    namespace: home-assistant
    valuesFile: values.yaml

resources:
  - ingress
