---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: omni-tools-ingressroute
  namespace: omni-tools
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`omni-tools.example.com`)
      services:
        - kind: Service
          name: omni-tools
          port: 80
