---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgresql

resources:
  - affine-db-sealed-secret.yaml
  - freshrss-db-sealed-secret.yaml
  - joplin-db-sealed-secret.yaml
  - postgresql-sealed-secret.yaml
  - transcribe-db-sealed-secret.yaml
