---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: freshrss

helmCharts:
  - name: freshrss
    repo: oci://registry.example.com/homelab/helm-charts
    version: 1.0.1
    releaseName: freshrss
    namespace: freshrss

resources:
  - ingress
